import keyMirror from 'keymirror'

export const ACTIONS = keyMirror({
  MASTERS_CONTAINER_GET_AUTHORS_REQUEST: null,
  MASTERS_CONTAINER_GET_AUTHORS_SUCCESS: null,
  MASTERS_CONTAINER_GET_AUTHORS_FAIL: null,

  MASTERS_CONTAINER_GET_BY_ID_REQUEST: null,
  MASTERS_CONTAINER_GET_BY_ID_SUCCESS: null,
  MASTERS_CONTAINER_GET_BY_ID_FAIL: null,

  MASTERS_CONTAINER_GET_ALL_GALLERY_REQUEST: null,
  MASTERS_CONTAINER_GET_ALL_GALLERY_SUCCESS: null,
  MASTERS_CONTAINER_GET_ALL_GALLERY_FAIL: null,

  MASTERS_CONTAINER_CLEAR_GALLERY_DETAIL: null
})

export const LOCAL_REDUCER = 'mastersContainerReducer'
export const LOCAL_SAGAS = 'mastersContainerSagas'
